#!/bin/sh
#
# Deploy to production server

# Run tests and build script

# Install dependencies
echo "Install dependencies"
composer install --no-dev --no-interaction

# Build theme
cd ./html/app/themes/tm-events-2016/
bower install
grunt build
cd ~/clone

# Set timestamp
echo "Set Time Stamp"
TIMESTAMP=$(date +%Y%m%d%H%M%S)

# Make a new releases folder
echo "Make new release folder"
ssh $USERNAME@$HOST "mkdir $DEPLOY_TO/releases/$TIMESTAMP"

# Copy files
echo "Copy files to server"
rsync -avz -e "ssh" --exclude="node_modules" --exclude="/media" --exclude="/app/languages" ./html/ $USERNAME@$HOST:$DEPLOY_TO/releases/$TIMESTAMP

# Symlink shared folders
echo "Symlink shared folders"
ssh $USERNAME@$HOST "ln -s $SHARED/media $DEPLOY_TO/releases/$TIMESTAMP/media"
ssh $USERNAME@$HOST "ln -s $SHARED/languages $DEPLOY_TO/releases/$TIMESTAMP/app/languages"

# Update app version
echo "Update app version"
ssh $USERNAME@$HOST "rm -rf $CURRENT;ln -s $DEPLOY_TO/releases/$TIMESTAMP/ $CURRENT"

# Record release timestamp
echo "Record successful release"
ssh $USERNAME@$HOST "echo $TIMESTAMP >> $DEPLOY_TO/releases/releases.log"
